name: Modern CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  quality-and-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Upgrade pip and install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install black==24.* flake8==7.* pytest==8.* pytest-mock

    - name: Code style (black)
      run: |
        black --check models/performance.py

    - name: Lint (flake8)
      run: |
        flake8 models/performance.py

    - name: Unit tests (core performance)
      run: |
        pytest tests/unit/test_models/test_performance.py -v